# -*- coding: utf-8 -*-
"""Template-Notebook-Bottleneck.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wz6CFBNobf6bABjTCYIubvg32NM1tInN

<div style="display: flex; background-color: RGB(255,114,0);" >
<h1 style="margin: auto; padding: 30px; ">ANALYSE DU STOCK ET DES VENTES DU SITE BOTTLENECK</h1>
</div>

# OBJECTIF DE CE NOTEBOOK

Bienvenue dans l'outil plébiscité par les analystes de données Jupyter.

Il s'agit d'un outil permettant de mixer et d'alterner code, texte et graphiques.

Cet outil est formidable pour plusieurs raisons:

+ Il permet de tester des lignes de codes au fur et à mesure de votre rédaction, de constater immédiatement le résultat d'une instruction, de la corriger si nécessaire.
+ Il permet aussi de rédiger du texte pour expliquer l'approche suivie ou les résultats d'une analyse et de le mettre en forme grâce à du code html ou plus simple avec **Markdown**
+ Il est possible d'ajouter des graphiques

Pour vous aider dans vos premiers pas à l'usage de Jupyter et de Python, nous avons rédigé ce notebook en vous indiquant les instructions à suivre.

Il vous suffit pour cela de saisir le code Python répondant à l'instruction donnée.

Vous verrez de temps à autre le code Python répondant à une instruction donnée mais cela est fait pour vous aider à comprendre la nature du travail qui vous est demandé.

Et gardez à l'esprit qu'il n'y a pas de solution unique pour résoudre un problème et qu'il y a autant de résolutions de problèmes que de développeurs ;)...

<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 1 - Importation des librairies et chargement des fichiers</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">1.1 - Importation des librairies</h3>
</div>
"""

#Importation de la librairie Pandas
import pandas as pd

#Importation de la librairie plotly express
import plotly.express as px

import numpy as np

#Trouver dans Google l'instruction permettant d'afficher toutes les colonnes d'un dataframe
#Saisir dans Google les mots clés "display all columns dataframe Pandas" par exemple.
#Dans les résultats de la recherche, privilégier les solutions provenant de Stack Overflow ou Medium

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">1.2 - Chargements des fichiers</h3>
</div>
"""

from google.colab import drive
drive.mount('/content/drive')

#Importation du fichier web.xlsx
df_web = pd.read_excel("/content/drive/MyDrive/OC/web.xlsx")
#Importation du fichier erp.xlsx
df_erp = pd.read_excel("/content/drive/MyDrive/OC/erp.xlsx")
#Importation du fichier liaison.xlsx
df_liaison = pd.read_excel("/content/drive/MyDrive/OC/liaison.xlsx")

"""<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 2 - Analyse exploratoire des fichiers</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1 - Analyse exploratoire du fichier erp.xlsx</h3>
</div>
"""

#Afficher les dimensions du dataset
print("Le tableau comporte {} observation(s) ou article(s)".format(df_erp.shape[0]))
print("Le tableau comporte {} colonne(s)".format(df_erp.shape[1]))

#Consulter le nombre de colonnes
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes
df_erp.info()

#Afficher les 5 premières lignes de la table
display(df_erp.head())

#Vérifier si il y a des lignes en doublon dans la colonne product_id
df_erp['product_id'].duplicated().any()

#Afficher les valeurs distinctes de la colonne stock_status
display(df_erp['stock_status'].unique())
#À quelle(s) autre(s) colonne(s) sont-elles liées ?
display(df_erp['stock_status'].value_counts())
display((df_erp['stock_quantity']<=0).sum())
display((df_erp['stock_quantity']>0).sum())

#Création d'une colonne "stock_status_2"
#La valeur de cette deuxième colonne sera fonction de la valeur dans la colonne "stock_quantity"
#Si la valeur de la colonne "stock_quantity" est nulle, renseigner "outofstock" sinon mettre "instock"
df_erp['stock_status_2'] = np.where(df_erp['stock_quantity'] == 0, 'outofstock', 'instock')
display(df_erp.head())

#Vérifions que les 2 colonnes sont identiques:
#Les 2 colonnes sont strictement identiques si les valeurs de chaque ligne sont strictement identiques 2 à 2
#La comparaison de 2 colonnes peut se réaliser simplement avec l'instruction ci-dessous:
df_erp["stock_status"] == df_erp["stock_status_2"]

#Le résultat est l'affichage de True ou False pour chacune des lignes du dataset
#C'est un bon début, mais difficile à exploiter

# Mais il est possible de synthétiser ce résultat en effectuant la somme de cette colonne:
# True vaut 1 et False 0
# Nous devrions obtenir la somme de 824 qui correspond au nombre de lignes dans ce dataset
(df_erp['stock_status'] == df_erp['stock_status_2']).sum()

#Si les colonnes ne sont absolument pas identiques ligne à ligne alors identifier la ligne en écart
##Dans ce cas je vous donne ce lien pour apprendre à réaliser des filtres dans Pandas:
##https://bitbucket.org/hrojas/learn-pandas/src/master/
##Lesson 3
display(df_erp[df_erp["stock_status"] != df_erp["stock_status_2"]])

#Corriger la ou les données incohérentes
df_erp['stock_status_2'] = np.where(df_erp['stock_quantity'] <= 0, 'outofstock', 'instock')
df_erp['stock_status'] = np.where(df_erp['stock_quantity'] <= 0, 'outofstock', 'instock')
#Vérification en utilisant le même code que plus haut pour afficher les problèmes
(df_erp['stock_status'] == df_erp['stock_status_2']).sum()

#Supprimer la colonne comportant le libellé "stock_status_2" car elle est redondante
#avec la colonne "stock_status".
del df_erp['stock_status_2']
display(df_erp.head())

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1.1 - Analyse exploratoire de chaque variable du fichier erp.xlsx</h3>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1.1.1 - Analyse de la variable PRIX</h3>
</div>
"""

###############
## LES PRIX  ##
###############

#Vérification des prix: Y a t-il des prix non renseignés, négatifs ou nuls?
#Afficher le ou les prix non renseignés dans la colonne "price"
display(df_erp['price'].isnull().sum())
#Afficher le prix minimum de la colonne "price"
display(df_erp['price'].min())
#Afficher le prix maximum de la colonne "price"
display(df_erp['price'].max())
#Afficher les prix inférieurs ou égal à 0 (qu'est-ce qu'il faut en faire ?)
display(df_erp[df_erp['price'] < 0])

#Afficher les produits dont price <= à purchase_price
display(df_erp[df_erp['price'] <= df_erp['purchase_price']])

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1.1.2 - Analyse de la variable STOCK</h3>
</div>
"""

#######################
### stock_quantity  ###
#######################

#Vérification de la colonne stock quantity
#Afficher la quantité minimum de la colonne "stock_quantity"
display(df_erp['stock_quantity'].min())
#Afficher la quantité maximum de la colonne "stock_quantity"
display(df_erp['stock_quantity'].max())
#Afficher les stocks inférieurs à 0 (qu'est-ce qu'il faut en faire ?)
display(df_erp[df_erp['stock_quantity'] < 0])

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1.1.3 - Analyse de la variable ONSALE_WEB</h3>
</div>
"""

#Vérification de la colonne onsale_web et des valeurs qu'elle contient. Que signifient-elles?
df_erp['onsale_web'].unique()

#Quelles sont les colonnes à conserver selon vous?
#Techniquement il faudrait faire un filtre sur onsale_web et garder les produits vendus sur le web
#mais on va tout garder, on sait jamais s'il y a eu des erreurs de manipulations en interne sur le logiciel

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.1.1.4 - Analyse de la variable prix d'achat</h3>
</div>
"""

######################
##   prix d'achat   ##
######################

#Vérification de la colonne purchase_price :
#Afficher le ou les prix non renseignés dans la colonne "purchase_price"
display(df_erp['purchase_price'].isnull().sum())
#Afficher le prix minimum de la colonne "purchase_price"
display(df_erp['purchase_price'].min())
#Afficher le prix maximum de la colonne "purchase_price"
display(df_erp['purchase_price'].max())

#afficher les produits dont le prix d'achat est supérieur ou égal au prix
display(df_erp[df_erp['purchase_price'] >= df_erp['price']])

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.2 - Analyse exploratoire du fichier web.xlsx</h3>
</div>

"""

#Dimension du dataset
#Nombre d'observations
print("Le tableau comporte {} observation(s)".format(df_web.shape[0]))
#Nombre de caractéristiques
print("Le tableau comporte {} colonne(s)".format(df_web.shape[1]))

#Consulter le nombre de colonnes
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes
df_web.info()

# perso : savoir s'il y a des doublons
display(df_web.duplicated().any())

# perso : suppression des doublons
df_web_clean = df_web[df_web['post_type'] == 'product']

# perso : savoir s'il y a des doublons
display(df_web_clean.duplicated().any())
display(df_web_clean.info())

# afficher les lignes sku est NaN
display(df_web_clean[df_web_clean['sku'].isnull()])

# afficher produit dont post name est pierre-jean-villa-condrieu-suspendu-2018
display(df_web_clean[df_web_clean['post_name'] == 'pierre-jean-villa-condrieu-suspendu-2018'])

# afficher produit dont post name est pierre-jean-villa-cote-rotie-fongeant-2017
display(df_web_clean[df_web_clean['post_name'] == 'pierre-jean-villa-cote-rotie-fongeant-2017'])

# perso : suppresion des lignes où sku est NaN
df_web_clean = df_web_clean.dropna(subset=['sku'])
display(df_web_clean.info())

# creation sku_2, si sku est vide alors post_title sinon sku
# df_web_clean['sku_2'] = np.where(df_web_clean['sku'].isnull(), df_web_clean['post_title'], df_web_clean['sku'])

# affichage sku est vide
# display(df_web_clean[df_web_clean['sku'].isnull()])

# remplacemenet sku par sku_2 et suppression sku_2
# df_web_clean['sku'] = df_web_clean['sku_2']
# del df_web_clean['sku_2']

#Selon vous, quelles sont les colonnes à conserver ?
print("sku, total_sales, product_type, post_title")

#Si vous avez défini des colonnes à supprimer, effectuer l'opération
colonnes_a_garder = ['sku', 'total_sales', 'product_type','post_title']
df_web_clean = df_web_clean[colonnes_a_garder]
display(df_web_clean.head())

#Visualisation des valeurs de la colonne sku
#Quelles sont les valeurs qui ne semblent pas respecter la régle de codification?
display(df_web_clean['sku'].unique())

#Si vous avez identifié des codes articles ne respectant pas la régle de codification, consultez-les
display(df_web_clean[df_web_clean['sku'] == "bon-cadeau-25-euros"])

#afficher les produits dont le total_sales est inférieur à 0
display(df_web_clean[df_web_clean['total_sales'] < 0])

#afficher les produits dont le product_type est vide
display(df_web_clean[df_web_clean['product_type'].isnull()])

#afficher les produits dont le post_title est vide
display(df_web_clean[df_web_clean['post_title'].isnull()])

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">2.3 - Analyse exploratoire du fichier liaison.xlsx</h3>
</div>
"""

#Dimension du dataset
#Nombre d'observations
print("Nombre d'observations : ",df_liaison.shape[0])
#Nombre de caractéristiques
print("Nombre de caractéristiques : ",df_liaison.shape[1])

#Consulter le nombre de colonnes
#La nature des données dans chacune des colonnes
#Le nombre de valeurs présentes dans chacune des colonnes
df_liaison.info()

#Les valeurs de la colonne "product_id" sont-elles toutes uniques?
df_liaison['product_id'].duplicated().any()

#Les valeurs de la colonne "id_web" sont-elles toutes uniques?
df_liaison['id_web'].duplicated().any()

#Avons-nous des articles sans correspondance?
display(df_liaison[df_liaison['id_web'].isnull()])

df_liaison[df_liaison['id_web'].duplicated(keep=False)]

# perso : suppression des lignes id_web est null
df_liaison_clean = df_liaison.dropna(subset=['id_web'])

df_liaison_clean.info()

df_liaison_clean['id_web'].duplicated().any()

"""<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 3 - Jonction des fichiers</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 3.1 - Jonction du fichier df_erp et df_liaison</h3>
</div>
"""

#Fusion des fichiers df_erp et df_liaison
df_merge = pd.merge(df_erp, df_liaison_clean, on='product_id', how='left')
display(df_merge.info())

#Y a t-il des lignes ne "matchant" pas entre les 2 fichiers?
display(df_merge[df_merge['id_web'].isnull()])

#creation d'une colonne onsale_web 2 : si id_web est pas null alors 1 sinon 0
df_merge['onsale_web_2'] = np.where(df_merge['id_web'].isnull(), 0, 1)

#creation d'une colonne onsale_web 3 : si onsale_web est 1 alors 1 sinon 0
df_merge['onsale_web_3'] = np.where(df_merge['onsale_web'] == 1, 1, 0)

#affichage onsale_web_2 pas égal à onsale_web_3
display(df_merge[df_merge['onsale_web_2'] != df_merge['onsale_web_3']])

#mise a jour de onsale_web (si un des deux colonnes est 1 alors 1 sinon 0)/ supression des colonnes redondantes
df_merge['onsale_web'] = np.where((df_merge['onsale_web_2'] == 1) | (df_merge['onsale_web_3'] == 1), 1, 0)

del df_merge['onsale_web_3']
del df_merge['onsale_web_2']

#creation df_merge_clean et filtre sur id_web non vide
df_merge_clean = df_merge[df_merge['id_web'].notnull()]

df_merge_clean.info()
display(df_merge_clean.head())

# suppression des NaN
#df_merge_clean = df_merge.dropna(subset=['id_web'])
#display(df_merge_clean.info())

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 3.2 - Jonction du fichier df_merge et df_web</h3>
</div>
"""

#Fusionner les datasets df_merge et df_web
df_merge_web = pd.merge(df_merge_clean, df_web_clean, left_on='id_web', right_on='sku', how='left')
df_merge_web.info()

#Avons-nous des lignes sans correspondance?
display(df_merge_web[df_merge_web['sku'].isnull()])

#des articles non créé ?

#creation d'une colonne onsale_web 2 : si sku est null alors 0 sinon 1
df_merge_web['onsale_web_2'] = np.where(df_merge_web['sku'].isnull(), 0, 1)

#affichage onsale_web différent de onsale_web_2
display(df_merge_web[df_merge_web['onsale_web'] != df_merge_web['onsale_web_2']])

#onsale_web_2 écrase onsale_web et suppression de onsale_web_2
df_merge_web['onsale_web'] = df_merge_web['onsale_web_2']
del df_merge_web['onsale_web_2']

#nouvelle database et filtre sur onsale_web 1
df_merge_web_clean = df_merge_web[df_merge_web['onsale_web'] == 1]

df_merge_web_clean.info()

# Perso : suppression des NaN
# df_merge_web_clean = df_merge_web.dropna(subset=['sku'])
# df_merge_web_clean.info()

#affichage product_type est null
display(df_merge_web_clean[df_merge_web_clean['product_type'].isnull()])

"""<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 4 - Analyse univariée des prix</h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.1 - Exploration par la visualisation de données</h3>
</div>
"""

#Création d'une boîte à moustache de la répartition des prix grâce à Pandas
df_merge_web_clean.boxplot(column='price')

#Autre méthode avec plotly express
fig = px.box(df_merge_web_clean, y='price', title="Répartition des prix")
fig.show()

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2 - Exploration par l'utilisation de méthodes statistiques</h3>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2.1 - Identification par le Z-index</h3>
</div>
"""

#Calculer la moyenne du prix
moyenne_price = df_merge_web_clean['price'].mean()
print("Moyenne du prix : ",moyenne_price)
#Calculer l'écart-type du prix
ecarttype_price = df_merge_web_clean['price'].std()
print("Écart-type du prix : ", ecarttype_price)
#Calculer le Z-score
df_merge_web_clean.loc[:,'price_zscore'] = (df_merge_web_clean['price'] - moyenne_price) / ecarttype_price
display(df_merge_web_clean.head())

#Quel est le seuil prix dont le z-score est supérieur à 3?
outliers = df_merge_web_clean[abs(df_merge_web_clean['price_zscore']) > 3]
display(outliers)

df_merge_web_clean.groupby('product_type')['price'].describe()

produits_suspects = df_merge_web_clean[df_merge_web_clean['price_zscore'].abs() > 3]
produits_suspects

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 4.2.2 - Identification par l'intervalle interquartile</h3>
</div>
"""

#Utilisation de la fonction "describe" de Pandas pour l'étude des mesures de dispersion
display(df_merge_web_clean['price'].describe())

# autre méthode ?
Q1 = df_merge_web_clean['price'].quantile(0.25)
Q3 = df_merge_web_clean['price'].quantile(0.75)
IQR = Q3 - Q1

# bornes
lower_bound = Q1 - 2 * IQR
upper_bound = Q3 + 2 * IQR

# filtre des outliers
outliers_2 = df_merge_web_clean[(df_merge_web_clean['price'] < lower_bound) |
                               (df_merge_web_clean['price'] > upper_bound)]

display(outliers_2)

#Définir un seuil pour les articles "outliers" en prix
# display(outliers)

#Définir le nombre d'articles et la proportion de l'ensemble du catalogue "outliers"
nb_outliers = outliers_2.shape[0]
proportion_outliers = nb_outliers / df_merge_web_clean.shape[0]*100
print("Nombre d'articles en outliers : ", nb_outliers)
print("Proportion de l'ensemble du catalogue : ", proportion_outliers)

#Selon vous, ces outliers sont-ils justifiés ? Comment le démontrer si cela est possible ?
print("il faut comparer avec les prix sur internet ?")

"""<div style="background-color: RGB(51,165,182);" >
<h2 style="margin: auto; padding: 20px; color:#fff; ">Etape 5 - Analyse univariée du CA, des quantités vendues, des stocks et de la marge ainsi qu'une analyse multivariée  </h2>
</div>

<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.1 - Analyse des ventes en CA</h3>
</div>
"""

##############################
# Calculer le CA du site web #
##############################

#Créer une colonne calculant le CA par article
df_merge_web_clean['ca_par_article'] = df_merge_web_clean['price'] * df_merge_web_clean['total_sales']
#Calculer la somme de la colonne "ca_par_article"
total_ca = df_merge_web_clean['ca_par_article'].sum()
#Ce résultat correspond au chiffre d'affaire du site web
print("Le CA du site web est de : ", total_ca)

###############################
# Palmarès des articles en CA #
###############################

#Effectuer le tri dans l'ordre décroissant du CA du dataset df_merge
df_merge_web_clean = df_merge_web_clean.sort_values(by='ca_par_article', ascending=False)
#Réinitialiser l'index du dataset par un reset_index
df_merge_web_clean = df_merge_web_clean.reset_index(drop=True)
#Afficher les 20 premiers articles en CA
print(df_merge_web_clean.head(20))
#Graphique en barre des 20 premiers articles avec plotly express
fig = px.bar(df_merge_web_clean.head(20), x='post_title', y='ca_par_article', title='Palmares des articles en CA')
fig.show()

#############################
# Calculer le 20 / 80 en CA #
#############################

#Créer une colonne calculant la part du CA de la ligne dans le dataset
df_merge_web_clean['part_ca'] = df_merge_web_clean['ca_par_article'] / total_ca
#Créer une colonne réalisant la somme cumulative de la colonne précedemment créée
df_merge_web_clean['part_ca_cumul'] = df_merge_web_clean['part_ca'].cumsum()
#Grâce aux deux colonnes créées précedemment, calculer le nombre d'articles représentant 80% du CA
somme_80 = df_merge_web_clean[df_merge_web_clean['part_ca_cumul'] <= 0.8].shape[0]
#Afficher la proportion que représente ce groupe d'articles dans le catalogue entier du site web
proportion_80 = somme_80 / df_merge_web_clean.shape[0]*100
print("Proportion des articles représentant 80% du CA : ", proportion_80)

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.2 - Analyse des ventes en quantité</h3>
</div>
"""

#####################################
# Palmarès des articles en quantité #
#####################################

#Effectuer le tri dans l'ordre décroissant de quantités vendues du dataset df_merge
df_merge_web_clean = df_merge_web_clean.sort_values(by='total_sales', ascending=False)
#Réinitialiser l'index du dataset par un reset_index
df_merge_web_clean = df_merge_web_clean.reset_index(drop=True)
#Afficher les 20 premiers articles en quantité
display(df_merge_web_clean.head(20))
#Graphique en barre des 20 premiers articles avec plotly express
fig = px.bar(df_merge_web_clean.head(20), x='post_title', y='total_sales', title='Palmares des articles en quantité')
fig.show()

#############################
# Calculer le 20 / 80 en CA #
#############################

#Créer une colonne calculant la part en quantité de la ligne dans le dataset
df_merge_web_clean['part_quantite'] = df_merge_web_clean['total_sales'] / df_merge_web_clean['total_sales'].sum()
#Créer une colonne réalisant la somme cumulative de la colonne précedemment créée
df_merge_web_clean['part_quantite_cumul'] = df_merge_web_clean['part_quantite'].cumsum()
#Grâce aux deux colonnes créées précedemment, calculer le nombre d'articles représentant 80% des ventes en quantité
nb_articles_80_qte = df_merge_web_clean[df_merge_web_clean['part_quantite_cumul'] <= 0.8].shape[0]
#Afficher la proportion que représente ce groupe d'articles dans le catalogue entier du site web
proportion_80_qte = nb_articles_80_qte / df_merge_web_clean.shape[0]*100
print("Proportion des articles représentant 80% des ventes en quantité : ", proportion_80_qte)

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.3 - Analyse des stocks</h3>
</div>
"""

######################################
# Calculer le nombre de mois de stock #
######################################

#Import de numpy (deja fait)

#Création de la colonne Rotation de stock
#Remplacement des "inf" par 0
#Effectuer le tri dans l'ordre décroissant du nombre de mois de stock dans le dataset df_merge
#df_merge_web_clean = df_merge_web_clean.sort_values(by='stock_quantity', ascending=False)
#Réinitialiser l'index du dataset par un reset_index
#df_merge_web_clean = df_merge_web_clean.reset_index(drop=True)
#Graphique en barre du flop 20 des produits qui ont le plus de mois de stock
#fig = px.bar(df_merge_web_clean.head(20), x='post_title', y='stock_quantity', title='Flop 20 des produits qui ont le plus de mois de stock')
#fig.show()

df_merge_web_clean['mois_stock'] = df_merge_web_clean['stock_quantity'] / df_merge_web_clean['total_sales']
df_merge_web_clean['mois_stock'].replace([np.inf, -np.inf], 0, inplace=True)
df_merge_web_clean['mois_stock'].fillna(0, inplace=True)
df_merge_web_clean = df_merge_web_clean.sort_values(by='mois_stock', ascending=False).reset_index(drop=True)

fig = px.bar(df_merge_web_clean.head(20), x='post_title', y='mois_stock', title='Flop 20 des produits selon les mois de stock')
fig.show()

####################################
# Valorisation des stocks en euros #
####################################

#Création de la colonne Valorisation des stocks en euros
df_merge_web_clean['valorisation_stock_euros'] = df_merge_web_clean['stock_quantity'] * df_merge_web_clean['purchase_price']
#Calculer la somme de la colonne "Valorisation_stock_euros"
somme_stock_euros = df_merge_web_clean['valorisation_stock_euros'].sum()
somme_stock_euros

##############################################
# Valorisation du nombre de produits en stock #
##############################################

#Calculer la somme de la colonne stock quantity
somme_stock_quantity = df_merge_web_clean['stock_quantity'].sum()
somme_stock_quantity

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.4 - Analyse du taux de marge</h3>
</div>
"""

df_merge_web_clean.info()

############################
# Analyse du taux de marge #
############################

#Création de la colonne Prix HT
df_merge_web_clean = df_merge_web_clean.sort_values(by='price', ascending=False)
df_merge_web_clean['prix_ht'] = df_merge_web_clean['price'] / 1.2
#Création de la colonne Taux de marge
df_merge_web_clean['taux_marge'] = (df_merge_web_clean['prix_ht'] - df_merge_web_clean['purchase_price']) / df_merge_web_clean['prix_ht'] *100
#Afficher le prix minimum de la colonne "taux_marge"
print("Taux de marge minimum de la colonne taux_marge (%): ", df_merge_web_clean['taux_marge'].min())
#Afficher le prix maximum de la colonne "taux_marge"
print("Taux de marge maximum de la colonne taux_marge (%): ", df_merge_web_clean['taux_marge'].max())

#Affichage de la ligne avec un taux de marge inférieur à 0
display(df_merge_web_clean[df_merge_web_clean['taux_marge'] < 0])

#Création d'un dataframe avec les taux positifs
df_taux_marge_pos = df_merge_web_clean[df_merge_web_clean['taux_marge'] > 0]
#Afficher le prix minimum de la colonne "taux_marge"
print("Prix minimum de la colonne taux_marge : ", df_taux_marge_pos['taux_marge'].min())
#Afficher le prix maximum de la colonne "taux_marge"
print("Prix maximum de la colonne taux_marge : ", df_taux_marge_pos['taux_marge'].max())

#Création d'un dataframe avec le taux de marge moyen par type de produit
df_taux_marge_moyen = df_taux_marge_pos.groupby('product_type')['taux_marge'].mean()
#Affichage dans un graphique du taux de marge par type de produit
fig = px.bar(df_taux_marge_moyen, x=df_taux_marge_moyen.index, y=df_taux_marge_moyen.values, title='Taux de marge par type de produit')
fig.show()

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.5 - Analyse des corrélations entre les variables stock, sales et price</h3>
</div>
"""

############################
# Analyse des corrélations #
############################

#Importation de Seaborn
import seaborn as sns
#Création d'une heatmap de corrélation avec les variables stock, sales et price
sns.heatmap(df_merge_web_clean[['stock_quantity', 'total_sales', 'price']].corr(), annot=True)
#On peut également créer un mask pour n'afficher qu'une demi heatmap
mask = np.triu(np.ones_like(df_merge_web_clean[['stock_quantity', 'total_sales', 'price']].corr()))

#Que peut-on conclure des corrélations ?
print("quand le stock augmente, les prix baissent et les ventes augmentent")

"""<div style="border: 1px solid RGB(51,165,182);" >
<h3 style="margin: auto; padding: 20px; color: RGB(51,165,182); ">Etape 5.6 - Mise à disposition de la nouvelle table sur un fichier Excel</h3>
</div>
"""

#Mettre le dataset df_merge sur un fichier Excel
df_merge_web_clean.to_excel('df_merge_web_clean.xlsx', index=False)
from google.colab import files
files.download('df_merge_web_clean.xlsx')
#Cette étape peut être utile pour partager le résultat du dataset obtenu avec les équipes.